services:
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=movie-rator
  
volumes:
  db-data:
